default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  host: localhost
  database: fleddit_development

test:
  <<: *default
  host: localhost
  database: fleddit_test

production:
  <<: *default
  database: fleddit_production
  username: fleddit
  password: <%= ENV['MYAPP_DATABASE_PASSWORD'] %>
